name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Clean build
      run: ./gradlew clean

    - name: Build APK Debug
      run: ./gradlew assembleDebug

    - name: Rename APK with version and date
      run: |
        VERSION_NAME="1.0.0"
        DATE=$(date +'%Y%m%d')
        mv app/build/outputs/apk/debug/app-debug.apk MelaporApp-v${VERSION_NAME}-debug-${DATE}.apk

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: MelaporApp-debug-apk
        path: MelaporApp-v*.apk
